### ISSUE TITLE
Dutch translation - rotator_language.h

### ISSUE THREAD

**Issue by waaslandwolf** [k3ng/k3ng_rotator_controller#22]
Thanks for this software. I'm in the middle of modifying my CDE Ham IV rotator for computer control. Would like to share my Dutch language translation to contribute.

73,
David ON4BDS

[rotator_language.h.txt](https://github.com/k3ng/k3ng_rotator_controller/files/34355/rotator_language.h.txt)

**Comment by k3ng** [comment]
Thanks, David!  I have incorporated this into version 2.0.2015111502.

73
Goody
K3NG
