### ISSUE TITLE
PWM Slow Down in Slow Start Phase

### ISSUE THREAD

**Issue by dh2wq** [k3ng/k3ng_rotator_controller#25]
Hi,
I'm new on BugReproting using Github so I hope I won't mess it up...

On Line 6993 *normal_az_speed_voltage* is used as start value for slow down. I would except *current_az_speed_voltage* here. In line 6990 the same value is used for debugging output.

I changed it on my local branch because my motor driver need current_az_speed_voltage on the above mentioned line to work correctly.

Thanks for this fine code of source code,
Olli, DH2WQ

**Comment by k3ng** [comment]
I agree.  Updated code posted.  Thanks!!

73
Goody
K3NG
