### ISSUE TITLE
Response to Yaesu GS232 command "C" on overlap

### ISSUE THREAD

**Issue by dh1tw** [k3ng/k3ng_rotator_controller#40]
Hey,

this question is not directly related to this software, but I hope somebody could help me out:

I'm currently writing a [web frontend for rotators](https://github.com/dh1tw/remoteRotator). Currently, the Yaesu G232 protocol is supported. However I don't have a yaesu rotator available here. 

The command ```C``` and ```C2``` allow to query the heading of the rotator. Can somebody confirm me the range of the response, in particular when the rotator is overlapping. Does the rotator return ```0...359``` or ```0...449``` ?

It would be useful to know in order to implement the visualisation of Overlap properly.

Any help appreciated!

73 Tobias
DH1TW

![screen shot 2017-10-03 at 01 47 55](https://user-images.githubusercontent.com/5188703/31199963-61d82758-a959-11e7-8b67-7ea1aca02537.png)

**Comment by k3ng** [comment]
I believe the standard behavior of the Yaesu unit is to respond with 0 to
359, not 0 to 450.  I can certainly add an option to the Arduino rotator
code to make it respond with 0 to 450, but that would naturally work only
with this project and not other implementations.

**Comment by dh1tw** [comment]
Hey Anthony,
thanks for the clarification. That helps. I think I found a way to detect overlap with the metadata the user can provide through cli flags. I prefer to be standard compliant :-)

BR Tobias
