### ISSUE TITLE
Start problem with Hy-Gain T-2X Rotator

### ISSUE THREAD

**Issue by iw5bms** [k3ng/k3ng_rotator_controller#55]
Hi, I'm using firmware and hardware  from Remote QTH and sometime I have problem because the start of rotation cw or ccw, is faster than the brake solenoid and the rotor obviously does not start.  I think that a small delay of 0,5 - 1 second should be enought to solve the problem. Thank you in advance if some friend could help me to solve this problem.
73 Maurizio iw5bms
![control_boxjpg](https://user-images.githubusercontent.com/35818420/48314720-a8550280-e5cd-11e8-907c-68b235e5eb27.jpg)

**Comment by ra1nb0w** [comment]
Hi, have you resolved this issue? 73

**Comment by iw5bms** [comment]
Hi, yes the K3NG rotor controller runnning in the right way.
73 Maurizio iw5bms

Scarica Outlook per iOS<https://aka.ms/o0ukef>
________________________________
Da: ra1nb0w <notifications@github.com>
Inviato: Monday, October 19, 2020 6:05:41 PM
A: k3ng/k3ng_rotator_controller <k3ng_rotator_controller@noreply.github.com>
Cc: iw5bms <m_fedi@hotmail.com>; Author <author@noreply.github.com>
Oggetto: Re: [k3ng/k3ng_rotator_controller] Start problem with Hy-Gain T-2X Rotator (#55)


Hi, have you resolved this issue? 73

**Comment by ra1nb0w** [comment]
thank you. you should close this issue.

**Comment by ra1nb0w** [comment]
Just a side question: do you have published somewhere the connection schematics between K3NG and the Hy-Gain controller? Or do you have entirely substituted the Hy-Gain controller? thank you
